<?php

function annotation_image_node_field_enabled($field_name) {
  static $enabled;

  if (!isset($enabled[$field_name])) {
    $enabled[$field_name] = db_result(db_query("SELECT annotate FROM {annotation_image_node_field} WHERE field_name = '%s'", $field_name));
  }

  return $enabled[$field_name];
}

function annotation_image_form_content_field_edit_form_alter(&$form, $form_state) {
  if ($form['#field']['type'] == 'image') {
    $form['#submit'][] = 'annotation_image_form_content_field_edit_form_submit';
    $form['widget']['annotation_image'] = array(
      '#type' => 'checkbox',
      '#title' => t('Annotate this field'),
      '#default_value' => annotation_image_node_field_enabled($form['#field']['field_name']),
      '#description' => t('Allows users to comment on regions of this image.'),
    );
  }
}

function annotation_image_form_content_field_edit_form_submit($form, &$form_state) {
  $record = array(
    'field_name' => $form['#field']['field_name'],
    'annotate' => $form_state['values']['annotation_image'],
  );
  db_query("DELETE FROM {annotation_image_node_field} WHERE field_name = '%s'", $record['field_name']);
  drupal_write_record('annotation_image_node_field', $record);
}
